spring:
  application:
    name: lost-found
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}  # 默认 dev
  config:
    import: optional:file:.env[.properties] # 支持本地.env文件

  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      url: ${SPRING_REDIS_URL:redis://localhost:6379/10}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: ${LOG_LEVEL:INFO}

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qg.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: FULL
    use-generated-keys: true
    cache-enabled: true


jwt:
  sign-key: ${JWT_SIGN_KEY}
  expire: ${JWT_EXPIRE}
  refresh-expire: ${JWT_REFRESH_EXPIRE}
  refresh-sign-key: ${JWT_REFRESH_SIGN_KEY}

aliyun:
  oss:
    endpoint: ${OSS_ENDPOINT}
    region: ${OSS_REGION:cn-beijing}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
